pull_request_rules:
  - name: Automatic update for PR
    conditions:
      - author = dependabot[bot]
    actions:
      update:
  - name: Automatic approve for Dependabot pull requests
    conditions:
      - author = dependabot[bot]
    actions:
      review:
        type: APPROVE
