queue_rules:
  # If you have other queues defined, add this at the end so it is processed last
  - name: dep-update
    batch_size: 10
    # Wait for up to 30 minutes for the batch to fill up
    batch_max_wait_time: 30 min
    queue_conditions:
      - author = dependabot[bot]

pull_request_rules:
  - name: Automatic approve for Dependabot pull requests
    conditions:
      - author = dependabot[bot]
    actions:
      review:
        type: APPROVE
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author = dependabot[bot]
      - "#approved-reviews-by>=1"
    actions:
      queue:
