name: Feature request
description: Suggest an idea for this project.
labels:
  - "enhancement"
body:
  - type: markdown
    attributes:
      value: |
        :information_source: You can join my community and request features in the dedicated group. [Join now](https://chat.whatsapp.com/DM6WaaTQ4IJ3VOe2ly6KJD)!
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description:
        A clear and concise description of what the problem is. Ex. I'm always
        frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description:
        A clear and concise description of any alternative solutions or features
        you've considered.
  - type: textarea
    attributes:
      label: Additional context
      description:
        Add any other context or screenshots about the feature request here.
