import fs from "fs";
import themes from "../themes/index";

const TARGET_FILE = "./themes/README.md";

function generateThemeMarkdown(theme: string): string {
  return `\`${theme}\`</br>![${theme}][${theme}]`;
}

function generateThemeLink(username: string, theme: string): string {
  return `[${theme}]: https://github-readme-profile-alpha.vercel.app/api?username=${username}&theme=${theme}`;
}

function createThemeRows(
  themesArray: string[],
  itemsPerRow: number,
  username: string
): { themesPreviewTable: string; themesPreviewLink: string } {
  let themesPreviewTable = "";
  let themesPreviewLink = "";

  for (let i = 0; i < themesArray.length; i += itemsPerRow) {
    const rowThemes = themesArray.slice(i, i + itemsPerRow);

    themesPreviewTable += `| ${rowThemes.map(generateThemeMarkdown).join(" | ")} |\n`;
    themesPreviewLink += rowThemes.map(theme => generateThemeLink(username, theme)).join("\n") + "\n";
  }

  return { themesPreviewTable, themesPreviewLink };
}

export function generateReadmeThemes(username: string): string {
  const availableThemes = Object.keys(themes);
  const itemsPerRow = 3;

  const { themesPreviewTable, themesPreviewLink } = createThemeRows(availableThemes, itemsPerRow, username);

  const readmeContent = `<!-- DO NOT EDIT THIS FILE DIRECTLY -->
## Available Themes

With inbuilt themes, you can customize the look of the card without doing any manual customization.

Use \`?theme=THEME_NAME\` parameter like so :-

\`\`\`md
![GitHub Profile](https://gh-readme-profile.vercel.app/api?username=${username}&theme=dark)
\`\`\`

## Themes Preview

|                   |                   |                   |
| :---------------: | :---------------: | :---------------: |
${themesPreviewTable}

Want to add a new theme? Consider reading the [contribution guidelines](/CONTRIBUTING.md#-themes-contribution) :D

${themesPreviewLink}`;

  return readmeContent;
}

const username = "FajarKim";

const generatedReadme = generateReadmeThemes(username);

fs.writeFileSync(TARGET_FILE, generatedReadme);
