import fs from "fs";
import locales from "../i18n/index";
import languageNames from "../i18n/languageNames";

const TARGET_FILE = "./i18n/README.md";

function generateTranslationsMarkdown(locale: string): string {
  return `${locale}`;
}

export function generateReadmeLocales(): string {
  const availableLocales = Object.keys(locales);

  let localesListTable = "";
  for (let i = 0; i < availableLocales.length; i += 1) {
    const localesSlice = availableLocales.slice(i, i + 1);
    const row = localesSlice.map(locale => generateTranslationsMarkdown(locale)).join("");
    localesListTable += `  <tr>
    <td><p align="center"><code>${row}</code></p></td>
    <td><p align="left">${languageNames[row]}</p></td>
    <td><p align="center">${Object.keys(locales[row]).length / 16 * 100}%</p></td>
  </tr>\n`;
  }

  const readmeContent = `<!-- DO NOT EDIT THIS FILE DIRECTLY -->
## Available Locales
Use \`?locale=LOCALE_CODE\` parameter like so :-

\`\`\`markdown
![GitHub Stats](https://gh-readme-profile.vercel.app/api?username=FajarKim&locale=id)
\`\`\`

## Locales List

<table>
  <tr>
    <td><p align="center"><b>Code</b></p></td>
    <td><p align="center"><b>Locale</b></p></td>
    <td><p align="center"><b>Progress</b></p></td>
  </tr>
${localesListTable}</table>

Want to add new translations? Consider reading the [contribution guidelines](https://github.com/FajarKim/github-readme-profile/blob/master/CONTRIBUTING.md#%EF%B8%8F-translations-contribution) :D
`;

  return readmeContent;
}

const generatedReadme = generateReadmeLocales();

fs.writeFileSync(TARGET_FILE, generatedReadme);
